AntiMagic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from AntiMagic import views
from hosts import views as hosts_views
from hosts import urls as hosts_urls
from assets import urls as assets_urls
from assets import rest_urls

urlpatterns = [
    url(r'^$', hosts_views.index, name='dashboard'),
    url(r'^admin/', admin.site.urls),
    url(r'^asset/', include(assets_urls)),
    url(r'^hosts/', include(hosts_urls)),
    url(r'^logout/$', hosts_views.acc_logout, name='logout'),
    url(r'^api/', include(rest_urls)),
    url(r'^login/$', hosts_views.acc_login, name='login'),
    url(r'^monitor/$', hosts_views.monitor_index, name='monitor'),
]

hosts/urls.py
#!/usr/bin/env python
# Name: urls.py
# Time:8/8/16 8:56 PM
# Author:luo1fly

from django.conf.urls import url
from hosts import views

urlpatterns = [
    url(r'^$', views.hosts_index, name='hosts'),
    url(r'^host_mgr/$', views.host_mgr, name='host_mgr'),
    url(r'^multi_cmd/$', views.multi_cmd, name='multi_cmd'),
    url(r'^submit_task/$', views.submit_task, name='submit_task'),
    url(r'^get_task_result/$', views.get_task_result, name='get_task_result'),
    url(r'^file_delivery/$', views.file_delivery, name='file_delivery'),
    url(r'^file_upload/$', views.file_upload, name='file_upload'),
]

hosts/models.py
from django.db import models
from hosts.cus_auth import UserProfile
# Create your models here.


class Host(models.Model):
    name = models.CharField(max_length=64)
    sn = models.CharField(max_length=128)
    # 此处sn不加非空约束是因为hostbiao可以包含虚拟机，我们cmdb中的server也不能直接外键关联到host表，后续可以通过第三方脚本来实现数据导入
    ip_address = models.GenericIPAddressField()
    port = models.IntegerField(default=22)
    idc = models.ForeignKey('IDC')
    system_type_choices = (
        ('linux', 'Linux'),
        ('windows', 'Windows'),
    )
    system_type = models.CharField(choices=system_type_choices, max_length=32, default='linux')
    enabled = models.BooleanField(default=1)
    memo = models.TextField(blank=1, null=1)
    date = models.DateTimeField(auto_now_add=1)

    def __str__(self):
        return "%s(%s)" % (self.name, self.ip_address)

    class Meta:
        unique_together = ('ip_address', 'port')
        # 联合唯一约束，要考虑虚拟机的情况
        verbose_name = u'远程主机'
        verbose_name_plural = u"远程主机"


class IDC(models.Model):
    name = models.CharField(max_length=64, unique=1)
    memo = models.TextField(blank=1, null=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'数据中心'
        verbose_name_plural = u"数据中心"


class HostUser(models.Model):
    auth_type_choices = (
        ('ssh-password', 'SSH/PASSWORD'),
        ('ssh-key', 'SSH/KEY'),
    )
    auth_type = models.CharField(choices=auth_type_choices, max_length=32, default='ssh-password')
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=128, blank=1, null=1)

    def __str__(self):
        return "(%s)%s" % (self.auth_type, self.username)

    class Meta:
        unique_together = ('auth_type', 'username', 'password')
        verbose_name = u'远程主机用户'
        verbose_name_plural = u"远程主机用户"


class HostGroup(models.Model):
    name = models.CharField(unique=1, max_length=64)
    memo = models.TextField(blank=1, null=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'主机组'
        verbose_name_plural = u"主机组"


class BindHostToUser(models.Model):
    host = models.ForeignKey("Host")
    host_user = models.ForeignKey("HostUser")
    # host_user= models.ManyToManyField("HostUser")
    host_groups = models.ManyToManyField("HostGroup")

    class Meta:
        unique_together = ('host', 'host_user')
        verbose_name = u'主机与用户绑定关系'
        verbose_name_plural = u"主机与用户绑定关系"

    def __str__(self):
        return '%s:%s' % (self.host.name, self.host_user.username)

    def get_groups(self):
        return ','.join([g.name for g in self.host_groups.select_related()])


class TaskLog(models.Model):
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    task_type_choices = (('multi_cmd', "CMD"), ('file_send', "批量发送文件"), ('file_get', "批量下载文件"))
    task_type = models.CharField(choices=task_type_choices, max_length=50)
    user = models.ForeignKey('UserProfile')
    hosts = models.ManyToManyField('BindHostToUser')
    cmd = models.TextField()
    expire_time = models.IntegerField(default=30)
    task_pid = models.IntegerField(default=0)   # master process pid
    note = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return "task_id:%s cmd:%s" % (self.id, self.cmd)

    class Meta:
        verbose_name = u'批量任务'
        verbose_name_plural = u'批量任务'


class TaskLogDetail(models.Model):
    child_of_task = models.ForeignKey('TaskLog')
    bind_host = models.ForeignKey('BindHostToUser')
    date = models.DateTimeField(auto_now_add=True)  # finished date
    event_log = models.TextField()
    result_choices = (('success', 'Success'), ('failed', 'Failed'), ('unknown', 'Unknown'))
    result = models.CharField(choices=result_choices, max_length=30, default='unknown')
    note = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return "child of:%s result:%s" %(self.child_of_task.id, self.result)

    class Meta:
        verbose_name = u'批量任务日志'
        verbose_name_plural = u'批量任务日志'

hosts/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from hosts import models, task, utils
import json
from django.utils.datastructures import MultiValueDictKeyError
# Create your views here.


@login_required
def index(request):
    return render(request, 'index.html', locals())


@login_required
def hosts_index(request):
    return render(request, 'hosts/dashboard.html', locals())


@login_required
def host_mgr(request):
    try:
        group_id = request.GET['groupid']
    except MultiValueDictKeyError as e:
        host_list = request.user.bind_hosts.select_related()
        group_name = '未分组'
    else:
        host_list = models.BindHostToUser.objects.filter(host_groups__id=group_id)
        group_name = models.HostGroup.objects.get(id=group_id)
    # print(locals())
    return render(request, 'hosts/host_mgr.html', locals())


@login_required
def multi_cmd(request):
    return render(request, 'hosts/multi_cmd.html', locals())


@login_required
def submit_task(request):
    try:
        task_type = request.POST['task_type']
    except MultiValueDictKeyError as e:
        return HttpResponse('chu cuo le, ni mei you chuan task_type')
    else:
        task_handler = task.Task(request)
        task_id = task_handler.call(task_type)  # backend func() returns
        return HttpResponse(json.dumps(task_id))


@login_required
def get_task_result(request):
    task_handler = task.Task(request)
    task_result = task_handler.get_task_result()
    # print(task_result)
    return HttpResponse(json.dumps(task_result, default=utils.datetime_to_strftime))


@login_required
def file_delivery(request):
    return render(request, 'hosts/multi_file_delivery.html', locals())


@csrf_exempt
@login_required
def file_upload(request):
    file_obj = request.FILES['filename']
    file_upload_path = utils.handle_upload_file(request, file_obj)
    return HttpResponse(json.dumps(file_upload_path))


@login_required
def assets_index(request):
    return render(request, 'assets/dashboard.html', locals())


@login_required
def monitor_index(request):
    return render(request, 'monitor/dashboard.html', locals())


@login_required
def acc_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def acc_login(request):
    if request.method == 'GET':    # 如果是GET方法则转到登陆页面
        return render(request, 'login.html', locals())
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)    # 如果验证通过，返回值为user对象，反之为None
        if user:
            login(request, user)     # 需要传递一个user对象和request
            # print(request)
            return HttpResponseRedirect('/')
        else:
            login_err = 'Username or Password error!'
            return render(request, 'login.html', locals())      # 将字符串对象传递给模版

templates/hosts/dashboard.html
{% extends 'base.html' %}
{% block sidebar %}
<ul id="hosts_sidebar" class="nav nav-sidebar">
    <li class="active"><a href="{% url 'host_mgr' %}">主机</a></li>
    <li><a href="{% url 'multi_cmd' %}">批量命令</a></li>
    <li><a href="{% url 'file_delivery' %}">文件分发</a></li>
    <li><a href="#">任务计划</a></li>
    <li><a href="#">审计</a></li>
</ul>
{% endblock %}

{% block content-panel %}
<h1>hosts</h1>
{% endblock %}

{% block bottom-js %}
{{ block.super }}
<script type="text/javascript">
    $("#hosts_sidebar a[href='{{ request.path }}']").parent().addClass('active');
    $("#hosts_sidebar a[href='{{ request.path }}']").parent().siblings().removeClass('active');
    $("#navbar a[href='{% url 'hosts' %}']").parent().addClass('active');
</script>
{% endblock %}

templates/hosts/host_list_component.html
 <div class="col-md-3">
        <div class="panel panel-default panel-left ">
            <div class="panel-body">
                <ul id="group-list" class="list-group">
                    <li class="list-group-item border-less">
                        <a href="#">未分组</a>
                        <span class="badge">{{ request.user.bind_hosts.select_related.count }}</span>
                    </li>
                    {% for group in request.user.host_groups.select_related %}
                    <li class="list-group-item border-less">
                        <input onclick="CheckAllToggle(this)" data="host-group" type="checkbox" value="{{ group.id }}">
                        <a class="a-pointer" data="group">{{ group.name }}</a>{# next() #}
                        <span class="badge">{{ group.bindhosttouser_set.select_related.count }}</span>{# next() #}
                        <ul class="list-group hide">{# next() #}
                            {% for h in group.bindhosttouser_set.select_related %}
                            <li class="list-group-item list-tree">{# children() #}
                                <span>-- </span>
                                <input data="bind-host" type="checkbox" value="{{ h.id }}">{# children('input') #}
                                {{ h.host.name }}({{ h.host_user.username }}@{{ h.host.ip_address }})
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

templates/hosts/host_mgr.html
{% extends 'hosts/dashboard.html' %}
{% block custom-style %}
{% endblock %}
{% block content-panel %}

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>host groups</h2>
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="{% url 'host_mgr' %}">未分组</a>
                        <span class="badge">{{ request.user.bind_hosts.select_related.count }}</span>
                    </li>
                    {% for group in request.user.host_groups.select_related %}
                    <li class="list-group-item">
                        <a href="{% url 'host_mgr' %}?groupid={{ group.id }}">{{ group.name }}</a>
                        <span class="badge">{{ group.bindhosttouser_set.select_related.count }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>{{ group_name }}</h2>
                <table class="table table-hover table-bordered">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>IP</th>
                        <th>IDC</th>
                        <th>RemoteUser</th>
                        <th>enabled</th>
                        <th>Login</th>
                    </tr>
                    {% for h in host_list%}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ h.host.name }}</td>
                        <td>{{ h.host.ip_address }}</td>
                        <td>{{ h.host.idc }}</td>
                        <td>{{ h.host_user.username }}</td>
                        <td>{{ h.host.enabled }}</td>
                        <td>Login</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/hosts/multi_cmd.html
{% extends 'hosts/dashboard.html' %}

{% block content-panel %}
{% include 'hosts/host_list_component.html' %}
    <div class="col-md-9">
        <div class="panel panel-default panel-right">
            <div class="panel-body">
                {% csrf_token %}
                {% include 'hosts/task_exec_component.html' %}
                <div id="err-msg"></div>
                <br/>
                <div id="result-box"></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
{{ block.super }}
{% include 'hosts/multi_task_js.html' %}
{% endblock %}

templates/hosts/multi_file_delivery.html
{% extends 'hosts/dashboard.html' %}

{% block custom-style-import %}
<link href="/static/plugins/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet">
{% endblock %}

{% block content-panel %}
{% include 'hosts/host_list_component.html' %}
    <div class="col-md-9">
        <div class="panel panel-default panel-right">
            <div class="panel-body">
                {% csrf_token %}
                <select  id="task_type" class="selectpicker">
                    <option value="file_send">分发文件到客户端</option>
                    <option value="file_get">从客户端下载文件</option>
                </select>

                <input id="file_upload" name="filename" type="file" multiple class="file-loading">
                <div class="form-group">
                    <label for="exampleInputName2">远程文件路径</label>
                    <input type="text" placeholder="必须输入绝对路径，不要包含文件名" class="form-control"
                           name="remote_file_path" id="remote_file_path" >
                </div>
                <button type="button" class="btn btn-success pull-right"
                        onclick="SubmitTask('multi_file_delivery')">执行任务</button>

                <div id="err-msg"></div>
                <br/>
                <div id="result-box"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottom-js %}
{% include 'hosts/multi_task_js.html' %}
{{ block.super }}
    <script src="/static/plugins/bootstrap-fileinput/js/fileinput.min.js"></script>
    <script src="/static/plugins/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js"></script>
    <script src="/static/plugins/bootstrap-fileinput/js/fileinput_locale_zh.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            upload_files = [];

            $("#file_upload").fileinput({
                uploadUrl: "{% url 'file_upload' %}", // server upload action
                uploadAsync: true,
                language:'zh',
                maxFileSize:2000,
                maxFileCount: 5,
            });

            $('#file_upload').on('fileuploaded', function(event, data, previewId, index) {
                var form = data.form, files = data.files, extra = data.extra,
                        response = data.response, reader = data.reader;
                console.log(response);
                upload_files.push(response);
            });

            $("#task_type").on("change",function(){
                if (this.value == 'file_send'){
                    $(".file-input").removeClass("hide");
                    $("#file-download-to-local").addClass("hide")
                }else{
                    $(".file-input").addClass("hide");
                    $("#file-download-to-local").removeClass("hide")
                }
            });//end on change
        });
    </script>

{% endblock %}

templates/hosts/multi_task_js.html
<script type="text/javascript">
    $(document).ready(function () {
        $("#group-list a[data='group']").click(function () {
            $(this).nextAll('ul').toggleClass('hide');
        });
    });

    function CheckAllToggle(ele){
        if(ele.checked){//把它下面所有的主机都 全选
            $(ele).next().next().next().children().children("input").prop("checked",true);
        }else{
            $(ele).next().next().next().children().children("input").prop("checked",false);
        };
    };

    function SubmitTask(task_type) {
        FormVerification(task_type);
    };

    function FormVerification(task_type) {
        var err_list = [];
        var data_dic = {};
        data_dic['task_type'] = task_type;
        data_dic['selected_hosts'] = SelectedHosts();
        if (data_dic['selected_hosts'].length == 0){
            err_list.push(['验证失败', '未选中任何主机']);
        }
        else {
            if (task_type == 'multi_cmd') {
                data_dic['cmd'] = $.trim($("textarea[name='cmd']").val());
                if (data_dic['cmd'].length == 0) {
                    err_list.push(['验证失败', '未输入要执行的命令']);
                }
            }
            else if (task_type == 'multi_file_delivery') {
                //从页面获取远程存放路径
                var remote_file_path = $.trim($('#remote_file_path').val());
                if (remote_file_path.length == 0) {
                    err_list.push(['验证失败', "未输入远程文件路径!"]);
                }
                else {
                    data_dic['remote_path'] = remote_file_path
                    //从页面选择上传还是下载功能
                    var action_type = $('#task_type').val();
                    data_dic['file_transfer_type'] = action_type;
                    if (action_type == 'file_send'){
                        //判断已上传到中转站的文件列表是否为空
                        if (upload_files.length == 0) {
                            err_list.push(['验证失败',"还未上传任何文件到中转机！"]);
                        }
                        else {
                            data_dic['upload_files'] = upload_files;
                        }
                    }
                    // else file_get not come true

                };
            };
        };

        if (err_list.length > 0){
            $("#err-msg").html("");
            $.each(err_list, function (index, item) {
                var err_msg = "<p style='color:red;'>" + index + ". " + item[1] + "</p>";
                $("#err-msg").append(err_msg);
            });
        }else {
            $("#err-msg").html("");
            data_dic['csrfmiddlewaretoken'] = $("input[name='csrfmiddlewaretoken']").attr('value')
            console.log(data_dic)
            $.post("{% url 'submit_task' %}", data_dic, function(callback){
                var task_id = JSON.parse(callback)
                RefreshGetTaskResult(task_id);
            });
        };

    };

    function SelectedHosts() {
        var selected_hosts = []
        var all_hosts = $("input[data='bind-host']")

        $.each(all_hosts, function (index, ele) {
            if (ele.checked){
                selected_hosts.push($(ele).val());
            };
        });
        return selected_hosts
    };

    function RefreshGetTaskResult(task_id) {
        setInterval(function () {
            GetTaskResult(task_id);
        },3000);
    };

    function GetTaskResult(task_id) {
        $.getJSON("{% url 'get_task_result' %}", {'task_id': task_id}, function(callback){
            console.log(callback);
            PrintOnPage(callback);
        });// end get
    };

    function PrintOnPage(result_list) {
        $("#result-box").html("")
        $.each(result_list, function (index, item) {
            var row_html = "<p>" + item.bind_host__host__name + "(" + item.bind_host__host__ip_address + ") ---->" + item.bind_host__host_user__username + " ------- " + item.date + " ------ " + item.result + "</p>" +
                "<pre>" + item.event_log + "</pre>";    //注意pre标签的用法
            $("#result-box").append(row_html);
        });
    };

</script>

templates/hosts/task_exec_component.html
<textarea name="cmd" class="form-control" rows="3" placeholder="输入要执行的命令..."></textarea>
<br/>
<button type="button" class="btn btn-success pull-right" onclick="SubmitTask('multi_cmd')">执行命令</button>